# Generated by Django 5.2.14 on 2026-05-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('city', models.CharField(default='Ижевск', max_length=80, verbose_name='Город')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('watch', 'Нужен контакт'), ('paused', 'Пауза')], default='active', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Агентство',
                'verbose_name_plural': 'Агентства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Инструмент')),
                ('category', models.CharField(max_length=80, verbose_name='Категория')),
                ('implementation_cost', models.CharField(max_length=120, verbose_name='Стоимость внедрения')),
                ('strengths', models.TextField(verbose_name='Плюсы')),
                ('weaknesses', models.TextField(verbose_name='Минусы')),
                ('expected_effect', models.TextField(verbose_name='Ожидаемый эффект')),
                ('fit_score', models.PositiveSmallIntegerField(default=5, verbose_name='Соответствие задаче, 1-10')),
            ],
            options={
                'verbose_name': 'Рыночный инструмент',
                'verbose_name_plural': 'Рыночные инструменты',
                'ordering': ['-fit_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=120, verbose_name='Проект')),
                ('building', models.CharField(max_length=40, verbose_name='Корпус')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('apartment_number', models.CharField(max_length=20, verbose_name='Квартира')),
                ('rooms', models.CharField(max_length=20, verbose_name='Комнатность')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь, кв. м')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена, руб.')),
                ('status', models.CharField(choices=[('available', 'Свободно'), ('reserved', 'Бронь'), ('sold', 'Продано')], default='available', max_length=20, verbose_name='Статус')),
                ('has_finish', models.BooleanField(default=False, verbose_name='Чистовая отделка')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Приоритетный лот')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
                'ordering': ['project', 'building', 'floor', 'apartment_number'],
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Баллы Resource Expert')),
                ('tier', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='silver', max_length=20, verbose_name='Статус')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtors', to='portal.agency', verbose_name='Агентство')),
            ],
            options={
                'verbose_name': 'Риелтор',
                'verbose_name_plural': 'Риелторы',
                'ordering': ['agency__name', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lead', 'Заведен лид'), ('booking', 'Создана бронь'), ('approved', 'Бронь подтверждена'), ('event', 'Участие в мероприятии')], max_length=20, verbose_name='Тип')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('description', models.CharField(max_length=240, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='portal.realtor', verbose_name='Риелтор')),
            ],
            options={
                'verbose_name': 'Активность партнера',
                'verbose_name_plural': 'Активность партнеров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО клиента')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('protected', 'Защищен'), ('conflict', 'Конфликт'), ('expired', 'Истек')], default='protected', max_length=20, verbose_name='Статус')),
                ('protected_until', models.DateTimeField(verbose_name='Защита до')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='portal.realtor', verbose_name='Риелтор')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает менеджера'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_type', models.CharField(choices=[('installment', 'Рассрочка 30/70 +15%'), ('mortgage', 'Ипотека'), ('cash', '100% оплата')], default='installment', max_length=20, verbose_name='Форма оплаты')),
                ('down_payment_percent', models.PositiveSmallIntegerField(default=30, verbose_name='Первоначальный взнос, %')),
                ('markup_percent', models.PositiveSmallIntegerField(default=15, verbose_name='Удорожание, %')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждена')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='portal.lead', verbose_name='Лид')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='portal.property', verbose_name='Лот')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='portal.realtor', verbose_name='Риелтор')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-created_at'],
            },
        ),
    ]
